# Hyprland entrypoint

source = /home/amalv/.config/hypr/conf/10-monitor.conf
source = /home/amalv/.config/hypr/conf/20-env.conf
source = /home/amalv/.config/hypr/conf/30-startup.conf
source = /home/amalv/.config/hypr/conf/40-input-layout.conf
source = /home/amalv/.config/hypr/conf/50-binds.conf
source = /home/amalv/.config/hypr/conf/60-gestures.conf
source = /home/amalv/.config/hypr/conf/70-windowrules.conf

# HyprMod managed settings
source = /home/amalv/.config/hypr/hyprland-gui.conf

# Noctalia managed colors
source = /home/amalv/.config/hypr/noctalia/noctalia-colors.conf
