ActivateCmd="/home/amalv/Documents/hyprland-tablet-backup/hyprland-surface/wvkbd-custom/scripts/show-wvkbd.sh"
DeactivateCmd="/home/amalv/Documents/hyprland-tablet-backup/hyprland-surface/wvkbd-custom/scripts/hide-wvkbd.sh"
