ActivateCmd="/usr/bin/bash -lc '$HOME/.local/src/hyprland-tablet/hyprland-surface/wvkbd-custom/scripts/show-wvkbd.sh'"
DeactivateCmd="/usr/bin/bash -lc '$HOME/.local/src/hyprland-tablet/hyprland-surface/wvkbd-custom/scripts/hide-wvkbd.sh'"
