$background = 130d0a
$onBackground = f9e0d8
$surface = 130d0a
$surfaceDim = 130d0a
$surfaceBright = 372924
$surfaceContainerLowest = 000000
$surfaceContainerLow = 1a110e
$surfaceContainer = 221714
$surfaceContainerHigh = 281d19
$surfaceContainerHighest = 30231e
$onSurface = f9e0d8
$surfaceVariant = 30231e
$onSurfaceVariant = bca69f
$outline = 84716b
$outlineVariant = 55443f
$inverseSurface = fff8f6
$inverseOnSurface = 5d534f
$shadow = 000000
$scrim = 000000
$surfaceTint = f8b8a0
$primary = f8b8a0
$primaryDim = e9aa93
$onPrimary = 603524
$primaryContainer = 764634
$onPrimaryContainer = ffdcd0
$inversePrimary = 845340
$primaryFixed = ffbda5
$primaryFixedDim = efaf98
$onPrimaryFixed = 4d2516
$onPrimaryFixedVariant = 6f412f
$secondary = e7beaf
$secondaryDim = d8b0a2
$onSecondary = 56392f
$secondaryContainer = 50352b
$onSecondaryContainer = dfb6a8
$secondaryFixed = ffdbcf
$secondaryFixedDim = f6cbbd
$onSecondaryFixed = 55392e
$onSecondaryFixedVariant = 745449
$tertiary = ffefd3
$tertiaryDim = ffdf9b
$onTertiary = 6e5721
$tertiaryContainer = ffdf9b
$onTertiaryContainer = 654f19
$tertiaryFixed = ffdf9b
$tertiaryFixedDim = f0d18e
$onTertiaryFixed = 503c07
$onTertiaryFixedVariant = 6f5822
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = a06a56
$secondaryPaletteKeyColor = 926f63
$tertiaryPaletteKeyColor = 8d743b
$neutralPaletteKeyColor = 817571
$neutralVariantPaletteKeyColor = 86736d
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = a06a56
$secondary_paletteKeyColor = 926f63
$tertiary_paletteKeyColor = 8d743b
$neutral_paletteKeyColor = 817571
$neutral_variant_paletteKeyColor = 86736d
$term0 = 353433
$term1 = ff5715
$term2 = ffbe93
$term3 = ffdfd1
$term4 = b9ab66
$term5 = f2907d
$term6 = ffbb7f
$term7 = efd3c5
$term8 = b49e95
$term9 = ff875f
$term10 = ffd5bb
$term11 = fff1ec
$term12 = dcbc93
$term13 = ffa995
$term14 = ffd3b0
$term15 = ffffff
$rosewater = ffeee9
$flamingo = ffdad0
$pink = ffd3cc
$mauve = ffaaa6
$red = ff9980
$maroon = faab97
$peach = ffbfa6
$yellow = ffeee6
$green = ffd9bb
$teal = ffdb94
$sky = e1df87
$sapphire = f2b2f2
$blue = ffa2bd
$lavender = ffbbbe
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = cf5d55
$kvisitedSelection = cf5d55
$knegative = e9582a
$knegativeSelection = e9582a
$kneutral = ff8b56
$kneutralSelection = ff8b57
$kpositive = f6910c
$kpositiveSelection = f6900d
$text = f9e0d8
$subtext1 = bca69f
$subtext0 = 84716b
$overlay2 = 74635d
$overlay1 = 63544f
$overlay0 = 534641
$surface2 = 443934
$surface1 = 342b27
$surface0 = 241c18
$base = 130d0a
$mantle = 130d0a
$crust = 120c09
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
